version: '3.8'
services:
  backend:
    build: https://github.com/zadoke/CPTrainBot-backend.git
    environment:
      - SERVER_PORT=3000
    ports:
      - "3000:3000"
  discord_bot:
    build: https://github.com/zadoke/CPTrainBot.git
    environment:
      - BACKEND_URL=http://backend:3000
      - CLIENT_ID=<insert your client id here>
      - TOKEN=<insert your token here>
    depends_on:
      - backend
